### PR TITLE
ISO 8601 appends "Z" to time to designate UTC timezone

### PR DESCRIPTION
**Pull request by snelg**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/kvz/locutus/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/kvz/locutus/pulls) for the same update/change?

### Description

ISO 8601 allows a "Z" appended to the time to designate UTC (i.e. instead of "+00:00", "+0000", or "+00").
Javascript's `Date.toISOString` uses this "trailing Z" format, which is why I noticed that it's missing from the current implementation of `strtotime`

I tried to keep the code changes to a minimum, so I adjusted the `reTzCorrection` regex instead of explicitly adding the "Z" to the `iso8601*` formats.
If that modified regex is too loose and incorrectly matches other cases, then feel free to toss out this PR and I'll take another whack at it.

### CODE REVIEW

**Comment by kukawski** [comment]
Thank you for the PR. I will try to review it during the coming weekend.
I didn't yet add full tz support to this function, but the "Z"-thingy seems to be a quick addition. Will also check compatibility with PHP.

**Comment by argosback** [comment]
@snelg resolve the conflict to merge your changes, thanks.

**Comment by snelg** [comment]
Merge conflict resolved.

**Comment by kukawski** [comment]
I can't approve the change, as it will break compatibility with PHP (as mentioned in my review comment above).
Additionally, this PR https://github.com/locutusjs/locutus/pull/432 already added basic support for timezones, which includes the "Z", so parsing of ISO 8601 should work now.

**Review by kukawski — CHANGES_REQUESTED** [review]

**Comment by snelg** [comment]
Yeah, PR #432 fixes my original issue, and is more robustly coded than my hack :)

**Pull request closed without merging**
