### PR TITLE
Use b64[char] instead of b64.indexOf(char) #193

### PR DESCRIPTION
**Pull request by duzun**
### Description
re-open [#193](https://github.com/kvz/locutus/pull/193)

By replacing b64 String with and Object and searching for char index in an object this function get twice faster (~ x2.5 faster according to my tests on run on a 340 chars long string). The bigger string, the bigger performance gain.
b64 object has to be computed only at first call to this function.

### CODE REVIEW

**Comment by kvz** [comment]
This relies on base64_decode.dict, where is that coming from?

**Comment by kukawski** [comment]
@kvz the dict is created and populated in lines 64-65.
I'm not sure about this approach. I'd probably prefer a function without side-effects.
For sure we could try to avoid the indexOf by creating the dict inside the function.

**Comment by kvz** [comment]
Ah spotted, thanks. Agreed with your take on this :ok_hand:

**Comment by divinity76** [comment]
btw 
```js
    h1 = b64[encodedData.charAt(i)]
    h2 = b64.indexOf(encodedData.charAt(++i))	    h2 = b64[encodedData.charAt(++i)]
    h3 = b64.indexOf(encodedData.charAt(++i))	    h3 = b64[encodedData.charAt(++i)]
    h4 = b64.indexOf(encodedData.charAt(++i))	    h4 = b64[encodedData.charAt(++i)]
```
should be even faster (`i++` creates a copy of the value, then increases the original by 1, then returns the copy; `++i` just increases the original and returns the original - this isn't a problem in C/C++, gcc auto-optimize this where applicable at -O1 and higher anyway, but i wouldn't trust browsers to do the same)

**Comment by kvz** [comment]
Closing for lack of activity, feel free to re-open the discussion

**Pull request closed without merging**
